title: Page

pages:
  template:
    - section_videobox
    - section_portfolio
    - section_slider

fields:
  title: title

  info:
    label: Hint
    type: info
    text: >
      Die Inhalte werden durch die einzelnen Unterseiten definiert.
